### ISSUE TITLE
Publish releases with binaries

### ISSUE THREAD

**Issue by ligurio** [AndreyAkinshin/perfolizer#9]
There is an assumption in a README that all users have installed .NET on his machines, see https://github.com/AndreyAkinshin/perfolizer#command-line-installation. It is not so. I'm using perfolizer and don't use .NET at all.  It would be great to publish Github releases with binaries for popular platforms.

**Comment by AndreyAkinshin** [comment]
Hello @ligurio. Since Perfolizer is still in the research phase, I decided to deprecate the command-line tool. I introduce too many breaking changes and it's too challenging to maintain the command-line version in addition to the primary API. At the moment, the library is available only as a NuGet package for .NET projects. Once the active research is finished and the main API is stabilized, I will consider an option to recover the command-line tool.
